AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Style/FileName:
  Exclude:
    - bin/scss-lint

Style/RescueModifier:
  Enabled: false
