language: ruby
cache: bundler
node_js:
  - "0.10"
rvm:
  - 2.1.5
before_script:
  - npm install -g bower
  - bower install
deploy:
  provider: heroku
  app: ggp-pension-guidance
  api_key:
    secure: bASAlGbdIIHSLR2gErxLUtDcgtJaFFbSxrmeAzyIvkYw947iWIXmQtqODFCLTrg3v202PoW5rI47fjWVr47GdjxIVJctQAbYJo3qNBXNU8Xdv+aU1EXH+22E0nAGA+ZO71KLmb+Wdc9+AXJ6KfqfABqQmIEI2OdBWbjuLZ9LOR4=
  on:
    repo: guidance-guarantee-programme/pension_guidance
