language: ruby
cache: bundler
env:
  global:
    - secure: "gBNL4RkCwf9ExKFVlnBBr6i/bY1xQydNoZ1xneXsmeqCwdqmuJMaZKJioLI/U2IJJjay50y1dr9X1ZuKRdC3Zrv0VTW5k77T0fX4AcqP0nAxz5Y0UyEE8VB0UZQMoZgpm+xT7QPNaJZqNTl0uBzADJzMyaWBhWNtwOGOfsOR0XY="
    - secure: "FbiGhJvoeOhQb4Ms+eQ9zRzJmBDBvuJySdSvhJ/ksulHRjpPLk/MQKezHH7XrveqKztrl5hTapjSWe+BdXlvPQelCVycXD4BjDrNodJvuBCqgRbvh6sQRZagxSuCqRpfbM35xrIgDnkB7eVVz/NBqm7HzI4rHwmxrtcdNYkOTvw="
node_js:
  - "0.10"
rvm:
  - 2.1.5
before_script:
  - npm install
after_script:
  - ./node_modules/.bin/travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
deploy:
  provider: heroku
  app: ggp-pension-guidance
  api_key:
    secure: bASAlGbdIIHSLR2gErxLUtDcgtJaFFbSxrmeAzyIvkYw947iWIXmQtqODFCLTrg3v202PoW5rI47fjWVr47GdjxIVJctQAbYJo3qNBXNU8Xdv+aU1EXH+22E0nAGA+ZO71KLmb+Wdc9+AXJ6KfqfABqQmIEI2OdBWbjuLZ9LOR4=
  on:
    repo: guidance-guarantee-programme/pension_guidance
